// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: table.sql

package database

import (
	"context"
)

const reset = `-- name: Reset :exec
TRUNCATE users
`

func (q *Queries) Reset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, reset)
	return err
}
